name: Bug report new
description: Create a report to help us improve CKSP
title: "[BUG] "
labels: ["bug"]
assignees: mathiasvatter
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please fill out the form below as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Provide a minimal CKSP code snippet that triggers the issue
        and describe the steps to reproduce it.
      placeholder: |
        ```cksp
        // Code snippet that causes the error
        ```
        
        Steps to reproduce:
        1. Use '...'
        2. Compile with '...'
        3. Run '...'
        4. See error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: |
        What actually happened?
        Include any error messages or unexpected behavior.
      placeholder: |
        ```ksp
        // Generated vanilla KSP code
        ```
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen instead?
      placeholder: |
        ```ksp
        // Expected vanilla KSP output
        ```
      render: markdown
    validations:
      required: true

  - type: input
    id: cksp_version
    attributes:
      label: CKSP Version
      description: Specify the version of CKSP you are using.
      placeholder: e.g. 0.0.7
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: arch
    attributes:
      label: OS Architecture
      options:
        - x86_64
        - arm64
    validations:
      required: true

  - type: checkboxes
    id: tooling
    attributes:
      label: Tooling
      options:
        - label: Using VS Code plugin
        - label: Using Sublime Text build system

  - type: textarea
    id: other
    attributes:
      label: Other relevant information
      description: |
        Any additional context that might help:
        IDE version, dependencies, Kontakt version, logs, etc.